"""Markdown output generation."""

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from .issue_tracker import IssueTracker
from .models import Issue, IssueStatus

logger = logging.getLogger(__name__)


class OutputGenerator:
    """Generates Markdown output file with scan results."""

    def __init__(self, output_path: Path):
        """Initialize the output generator.

        Args:
            output_path: Path to the output Markdown file.
        """
        self.output_path = output_path

    def write(self, tracker: IssueTracker, scan_info: Optional[dict] = None) -> None:
        """Write the full output file.

        Rewrites the entire file with current issue state.

        Args:
            tracker: Issue tracker with current issues.
            scan_info: Optional scan metadata (files scanned, etc.)
        """
        content = self._generate_content(tracker, scan_info)

        try:
            with open(self.output_path, "w", encoding="utf-8") as f:
                f.write(content)
            logger.debug(f"Wrote output to {self.output_path}")
        except IOError as e:
            logger.error(f"Failed to write output file: {e}")
            raise

    def _generate_content(
        self,
        tracker: IssueTracker,
        scan_info: Optional[dict] = None,
    ) -> str:
        """Generate the Markdown content.

        Args:
            tracker: Issue tracker with current issues.
            scan_info: Optional scan metadata.

        Returns:
            Complete Markdown content.
        """
        lines: list[str] = []

        # Header
        lines.append("# Code Scanner Results")
        lines.append("")
        lines.append(f"*Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}*")
        lines.append("")

        # Summary
        stats = tracker.get_stats()
        lines.append("## Summary")
        lines.append("")
        lines.append(f"- **Open Issues:** {stats['open']}")
        lines.append(f"- **Resolved Issues:** {stats['resolved']}")
        lines.append(f"- **Total Issues:** {stats['total']}")
        lines.append("")

        # Scan info
        if scan_info:
            lines.append("## Scan Information")
            lines.append("")
            if "files_scanned" in scan_info:
                lines.append(f"- **Files Scanned:** {len(scan_info['files_scanned'])}")
            if "skipped_files" in scan_info:
                lines.append(f"- **Files Skipped:** {len(scan_info['skipped_files'])}")
            if "checks_run" in scan_info:
                checks_run = scan_info['checks_run']
                total_checks = scan_info.get('total_checks', checks_run)
                lines.append(f"- **Checks Run:** {checks_run}/{total_checks}")
            lines.append("")

        # Issues by file
        issues_by_file = tracker.get_issues_by_file()

        if not issues_by_file:
            lines.append("## Issues")
            lines.append("")
            lines.append("*No issues detected.*")
            lines.append("")
        else:
            lines.append("## Issues by File")
            lines.append("")

            for file_path, issues in issues_by_file.items():
                lines.append(f"### `{file_path}`")
                lines.append("")

                for issue in issues:
                    lines.extend(self._format_issue(issue))
                    lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Generated by Code Scanner*")

        return "\n".join(lines)

    def _format_issue(self, issue: Issue) -> list[str]:
        """Format a single issue as Markdown.

        Args:
            issue: The issue to format.

        Returns:
            List of Markdown lines.
        """
        lines: list[str] = []

        # Status badge
        status_badge = "🔴 OPEN" if issue.status == IssueStatus.OPEN else "✅ RESOLVED"

        lines.append(f"#### Line {issue.line_number} - {status_badge}")
        lines.append("")

        # Metadata
        lines.append(f"**Detected:** {issue.timestamp.strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("")
        lines.append(f"**Check:** {issue.check_query}")
        lines.append("")

        # Description
        lines.append("**Issue:**")
        lines.append("")
        lines.append(issue.description)
        lines.append("")

        # Code snippet if available
        if issue.code_snippet:
            lines.append("**Problematic Code:**")
            lines.append("")
            lines.append("```")
            lines.append(issue.code_snippet)
            lines.append("```")
            lines.append("")

        # Suggested fix
        if issue.suggested_fix:
            lines.append("**Suggested Fix:**")
            lines.append("")
            lines.append("```")
            lines.append(issue.suggested_fix)
            lines.append("```")
            lines.append("")

        return lines
